### ISSUE TITLE
Should edit output of git remote show origin to obtain url in .git_filters/RevDateURL.smudge using perl, not unix shell commands

### ISSUE THREAD

**Issue by eliotmiranda** [OpenSmalltalk/vm#2]
in .git_filters/RevDateURL.smudge the URL is obtained with "git remote get-url origin", but that doesn't work on Mac OS X git version 1.9.5 (Apple Git-50.3).  Instead one has to use git remote show origin.

I'm modifying .git_filters/RevDateURL.smudge to read

$url=`git remote get-url origin 2>/dev/null`;
if (!$url) { $url=`git remote show origin | grep -i fetch | sed 's/^.*URL: //' 2>/dev/null` }
$url =~ s/\s+$//m;

But it strikes me that the editing down from

* remote origin
  Fetch URL: http://github.com/OpenSmalltalk/vm
  Push  URL: http://github.com/OpenSmalltalk/vm
  HEAD branch: Cog
  Remote branches:
    Cog                    tracked
    master                 tracked
    oldTrunk               tracked
    platform/Cross/plugins tracked
    platform/win32/plugins tracked
  Local branch configured for 'git pull':
    Cog merges with remote Cog
  Local ref configured for 'git push':
    Cog pushes to Cog (up to date)

to

Fetch URL: http://github.com/OpenSmalltalk/vm

and thence to

http://github.com/OpenSmalltalk/vm

would best be done in Perl.  So anyone who's motivated, please fix my poor fix.

**Comment by timfel** [comment]
Fixed as part of cb649461c19531b6d254ee3be367b464ca267ecd
