### ISSUE TITLE
README.md should include description of check-in & contribution processes, etc

### ISSUE THREAD

**Issue by eliotmiranda** [OpenSmalltalk/vm#3]
README.md does describe the contents of the repository but it is thin on how to interact with the repository at a process level.  The README should
- tell people how the repository is managed (master vs branches etc)
- tell people how to submit issues with the repository (such as this issue)
- tell people how to become a member, get promoted to an admin etc.

**Comment by rmacnak** [comment]
This information should be in a file named CONTRIBUTING.md, which will cause GitHub to a display a link to it whenever anyone creates a pull request.

https://github.com/blog/1184-contributing-guidelines
